In [1]:
#Question 1
from collections import deque


In [2]:
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=' ')

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                queue.append(neighbor)
                visited.add(neighbor)


In [3]:
graph={
    0:[1, 3],
    1:[0, 2, 3],
    2:[1, 4, 5],
    3:[0, 1, 4],
    4:[2, 3, 5],
    5:[2, 4]
}


In [5]:

start_vertex = 0
bfs(graph, start_vertex)



0 1 3 2 4 5 

In [6]:
#Question 2
def dfs2(graph, start):
    visited = set()
    stack = [start]

    while stack:
        vertex = stack.pop()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)

            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

In [7]:
graph = {
    'A': ['B', 'S'],
    'B': ['A'],
    'C': ['D', 'E', 'F', 'S'],
    'D': ['C'],
    'E': ['C', 'H'],
    'F': ['C', 'G'],
    'G': ['F', 'H', 'S'],
    'H': ['E', 'G'],
    'S': ['A', 'C', 'G']
}

In [9]:
start_vertex='A'
dfs2(graph, start_vertex)

A S G H E C F D B 

In [40]:
#Question 3
import numpy as np
from queue import PriorityQueue



In [41]:
initial_state = np.array([[2, 8, 3],
                          [1, 6, 4],
                          [7, 0, 5]])

goal_state = np.array([[1, 2, 3],
                        [8, 0, 4],
                        [7, 6, 5]])

In [50]:
# Node class to represent states
class Node:
    def __init__(self, state, parent=None, g_score=0, h_score=0):
        self.state = state
        self.parent = parent
        self.g_score = g_score
        self.h_score = h_score
        self.f_score = g_score + h_score

    def __lt__(self, other):
        return self.f_score < other.f_score


In [51]:
def heuristic(state):
    return np.sum(state != goal_state)

In [52]:
def get_successors(state):
    successors = []
    zero_position = np.argwhere(state == 0)[0]

    for action in [(0, 1), (1, 0), (0, -1), (-1, 0)]:
        new_position = zero_position + action
        if np.all(new_position >= 0) and np.all(new_position < state.shape):
            new_state = state.copy()
            new_state[zero_position[0], zero_position[1]] = state[new_position[0], new_position[1]]
            new_state[new_position[0], new_position[1]] = 0
            successors.append(new_state)

    return successors


In [53]:
def astar(start_state, goal_state, heuristic):
    priority_queue = PriorityQueue()
    priority_queue.put((0, Node(start_state)))

    while not priority_queue.empty():
        _, current_node = priority_queue.get()

        if np.array_equal(current_node.state, goal_state):
            # Goal state reached, reconstruct path
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]

        for successor_state in get_successors(current_node.state):
            new_cost = current_node.g_score + 1
            new_node = Node(successor_state, parent=current_node, g_score=new_cost, h_score=heuristic(successor_state))
            priority_queue.put((new_node.f_score, new_node))

    return None

In [54]:
result_path = astar(initial_state, goal_state, heuristic)

# Printing result
if result_path is not None:
    print("Solution found:")
    for state in result_path:
        print(state)
else:
    print("Goal state is not reachable.")

Solution found:
[[2 8 3]
 [1 6 4]
 [7 0 5]]
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[1 2 3]
 [0 8 4]
 [7 6 5]]
[[1 2 3]
 [8 0 4]
 [7 6 5]]
